const express = require("express");

const router = express.Router();

const itemControllers = require("./controllers/itemControllers");

const questions = [
  {
    id: 1,
    question: "Quel est votre budget de voyage pour les vacances ?",
    options: [
      {
        id: 1,
        option: "Moins de 1000€",
        value: "low",
        countries: [
          "Maroc",
          "Turquie",
          "Thaïlande",
          "Indonésie",
          "Tunisie",
          "Hong Kong",
          "Andorre",
          "Macau",
          "Bulgaria",
          "Romania",
        ],
      },
      {
        id: 2,
        option: "Entre 1000€ et 5000€",
        value: "medium",
        countries: [
          "Espagne",
          "Grèce",
          "Italie",
          "Portugal",
          "Mexique",
          "Allemagne",
          "Royaume-Uni",
          "États-Unis",
          "France",
          "Chine",
          "Hongrie",
          "Autriche",
          "Danemark",
          "Croatie",
          "Russie",
          "Pays-Bas",
          "Malaisie",
          "Japon",
          "Afrique du Sud",
          "Puerto Rico",
          "Vietnam",
          "Belarus",
          "Ukraine",
          "Latvia",
          "Belgique",
          "Corée du Sud",
          "Lituanie",
          "Kazakhstan",
          "Suède",
          "Australie",
        ],
      },
      {
        id: 3,
        option: "Plus de 5000€",
        value: "high",
        countries: [
          "Japon",
          "Maldives",
          "Nouvelle-Zélande",
          "Australie",
          "Dubai",
          "Koweït",
          "Bahrain",
          "Bahamas",
          "Estonie",
          "Iran",
          "Géorgie",
          "Philippines",
          "Singapour",
          "Émirats arabes unis",
        ],
      },
    ],
  },
  {
    id: 2,
    question: "Quel type de climat préférez-vous ?",
    options: [
      {
        id: 1,
        option: "Chaud et ensoleillé",
        value: "hot",
        countries: [
          "Thaïlande",
          "Mexique",
          "République Dominicaine",
          "Indonésie",
          "Australie",
          "Maroc",
          "Turquie",
          "Tunisie",
          "Hong Kong",
          "Andorre",
          "Macau",
          "Bulgaria",
          "Romania",
        ],
      },
      {
        id: 2,
        option: "Tempéré et doux",
        value: "temperate",
        countries: [
          "France",
          "Japon",
          "Australie",
          "Canada",
          "États-Unis",
          "Italie",
          "Portugal",
          "Mexique",
          "Allemagne",
          "Royaume-Uni",
          "France",
          "Chine",
          "Hongrie",
          "Autriche",
          "Danemark",
          "Croatie",
          "Russie",
          "Pays-Bas",
          "Malaisie",
          "Japon",
          "Afrique du Sud",
          "Puerto Rico",
          "Vietnam",
          "Belarus",
          "Ukraine",
          "Latvia",
          "Belgique",
          "Corée du Sud",
          "Lituanie",
          "Kazakhstan",
          "Suède",
        ],
      },
      {
        id: 3,
        option: "Froid et enneigé",
        value: "cold",
        countries: [
          "Canada",
          "Norvège",
          "Suède",
          "Finlande",
          "Islande",
          "Koweït",
          "Bahrain",
          "Bahamas",
          "Estonie",
          "Iran",
          "Géorgie",
          "Philippines",
          "Singapour",
          "Émirats arabes unis",
        ],
      },
    ],
  },
  {
    id: 3,
    question: "Quel type de vacances préférez-vous ?",
    options: [
      {
        id: 1,
        option: "Aventure",
        value: "adventure",
        countries: [
          "Népal",
          "Australie",
          "Pérou",
          "Afrique du Sud",
          "Costa Rica",
          "Maroc",
          "Turquie",
          "Thaïlande",
          "Indonésie",
          "Tunisie",
        ],
      },
      {
        id: 2,
        option: "Culturelles",
        value: "cultural",
        countries: [
          "Japon",
          "Inde",
          "Égypte",
          "Italie",
          "Mexique",
          "France",
          "Japon",
          "Australie",
          "Canada",
          "Maroc",
          "États-Unis",
        ],
      },
      {
        id: 3,
        option: "Détente",
        value: "relaxing",
        countries: [
          "Maldives",
          "Bali",
          "Thaïlande",
          "Seychelles",
          "Bahamas",
          "Espagne",
          "Grèce",
          "Italie",
          "Portugal",
          "Mexique",
          "Afrique du Sud",
          "Pérou",
          "Costa Rica",
          "Népal",
          "Turquie",
          "Islande",
          "République Dominicaine",
          "Indonésie",
          "Maroc",
          "Australie",
          "Canada",
          "États-Unis",
          "France",
          "Japon",
          "Inde",
          "Égypte",
          "Italie",
          "Mexique",
          "Espagne",
          "Grèce",
          "Portugal",
          "Mexique",
          "Inde",
          "Égypte",
          "France",
          "Japon",
          "Australie",
          "Canada",
          "États-Unis",
          "France",
          "Japon",
          "Maldives",
          "Bali",
          "Seychelles",
          "Bahamas",
          "Espagne",
          "Grèce",
          "Italie",
          "Portugal",
          "Mexique",
        ],
      },
    ],
  },
  {
    id: 4,
    question: "Quel type de cuisine préférez-vous ?",
    options: [
      {
        id: 1,
        option: "Cuisine locale",
        value: "local",
        countries: [
          "Maroc",
          "Thaïlande",
          "Italie",
          "France",
          "Espagne",
          "Japon",
          "Grèce",
          "Portugal",
          "Turquie",
          "Inde",
          "Égypte",
        ],
      },
      {
        id: 2,
        option: "Cuisine internationale",
        value: "international",
        countries: [
          "États-Unis",
          "Australie",
          "Singapour",
          "Canada",
          "Mexique",
          "Chine",
          "Brésil",
          "Argentine",
          "Corée du Sud",
          "Russie",
          "Afrique du Sud",
        ],
      },
      {
        id: 3,
        option: "Cuisine gastronomique",
        value: "gastronomic",
        countries: [
          "France",
          "Espagne",
          "Japon",
          "Italie",
          "Belgique",
          "Suisse",
          "Australie",
          "Suède",
          "Danemark",
          "Pays-Bas",
          "Royaume-Uni",
        ],
      },
    ],
  },
  {
    id: 5,
    question:
      "Quelle est la période de l'année où vous souhaitez partir en vacances ?",
    options: [
      {
        id: 1,
        option: "Printemps (mars-mai)",
        value: "spring",
        countries: [
          "Japon",
          "Maroc",
          "Turquie",
          "Italie",
          "Portugal",
          "Espagne",
          "Grèce",
          "Thaïlande",
          "Indonésie",
          "Mexique",
          "Inde",
          "Égypte",
        ],
      },
      {
        id: 2,
        option: "Été (juin-août)",
        value: "summer",
        countries: [
          "Espagne",
          "Grèce",
          "Thaïlande",
          "Indonésie",
          "Mexique",
          "France",
          "Italie",
          "Portugal",
          "Turquie",
          "Maroc",
          "Australie",
          "Canada",
        ],
      },
      {
        id: 3,
        option: "Automne (septembre-novembre)",
        value: "autumn",
        countries: [
          "France",
          "Norvège",
          "Canada",
          "États-Unis",
          "Italie",
          "Royaume-Uni",
          "Allemagne",
          "Russie",
          "Chine",
          "Brésil",
          "Argentine",
        ],
      },
      {
        id: 4,
        option: "Hiver (décembre-février)",
        value: "winter",
        countries: [
          "Canada",
          "Finlande",
          "Islande",
          "Nouvelle-Zélande",
          "Suisse",
          "Suède",
          "Danemark",
          "Norvège",
          "Russie",
          "Autriche",
          "Allemagne",
        ],
      },
    ],
  },
];

router.get("/", (req, res) => {
  res.send(questions);
});

router.get("/items", itemControllers.browse);
router.get("/items/:id", itemControllers.read);
router.put("/items/:id", itemControllers.edit);
router.post("/items", itemControllers.add);
router.delete("/items/:id", itemControllers.destroy);

module.exports = router;
